// === fluxai.js ===
const axios = require("axios");

module.exports = {
  pattern: "fluxai",
  desc: "Generate an image using AI.",
  category: "main",
  filename: __filename,
  use: ".fluxai prompt",

  execute: async (conn, mek, m, { from, reply, q }) => {
    try {
      if (!q) return reply("Please provide a prompt for the image.");

      await reply("> *CREATING IMAGINE ...🔥*");

      const apiUrl = `https://api.siputzx.my.id/api/ai/flux?prompt=${encodeURIComponent(q)}`;

      const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

      if (!response || !response.data) {
        return reply("Error: The API did not return a valid image. Try again later.");
      }

      const imageBuffer = Buffer.from(response.data, "binary");

      // Send reaction
      await conn.sendMessage(from, {
        react: {
          text: "🚀",
          key: mek.key
        }
      });

      await conn.sendMessage(from, {
        image: imageBuffer,
        caption: `💸 *Imagine Generated By BLUE-XMD*-LITE 🚀\n✨ Prompt: *${q}*`
      }, { quoted: mek });

    } catch (error) {
      console.error("FluxAI Error:", error);
      reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
    }
  }
};